name: Cloudflare Pages Deployment
on:
  push:
    branches:
      - main

jobs:
  master:
    name: Cloudflare Pages
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GH_AUTOMATION_TOKEN }}
      - name: 'Create env file'
        run: |
          touch .env
          echo REACT_APP_API_URL=https://airdrop-be.subwallet.app/api >> .env
          echo GENERATE_SOURCEMAP=false >> .env
      - name: Build
        run: |
          yarn install --no-immutable
          CI=false yarn build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'sw-faucet'
          gitHubToken: ${{ secrets.GH_AUTOMATION_TOKEN }}
          branch: 'main'
          directory: './build'
          wranglerVersion: '3'
